### ISSUE TITLE
Update Chromium

### ISSUE THREAD

**Issue by JaccoGoris** [getnamo/BLUI#11]
Currently the chromium is still 48, which is pretty outdated (doesn't support css-grid for example) is there a clear guide on how to upgrade the CEF? I could attempt it and make a PR

**Comment by getnamo** [comment]
See https://github.com/getnamo/BLUI/issues/9 for the process. It's a bit involved process, but if you stick to it and follow the links it should make sense. If it's still confusing I'll try to get more detailed instructions.

**Comment by getnamo** [comment]
Updated in latest release: https://github.com/getnamo/BLUI/releases/tag/3.7.0

It should also be a x64 release process/wrapper. See https://github.com/getnamo/BluBrowser/ for process (it's pretty vague still because there are a lot of steps to fix/tweak releases)

**Comment by getnamo** [comment]
Closing in favor of https://github.com/getnamo/BLUI/issues/29. Post feedback there
