### ISSUE TITLE
Mouse interaction example

### ISSUE THREAD

**Issue by k164v** [getnamo/BLUI#19]
First of all, thank you for maintaining this awesome browser plugin for ue4! As an independent developer, it is very good to know someone are putting efforts into developing something so useful.

I know it has already been mentioned in the previous comments, but is it possible what we can have an example of how to use mouse to interact with the plugin or simple way of use the plugin as a texture?

Best Regards,
K

**Comment by oivio** [comment]
by this weekend I will present demo with examples

**Comment by k164v** [comment]
Thank you very much for your response!

**Comment by oivio** [comment]
> Thank you very much for your response!

np: there is already demo available to download getnamo did already add it in "realease" section. And here is demonstration https://www.youtube.com/watch?v=PRxO0yCO3Kk  PS: I'm still working on new update with more clean instruction and demonstration also included some additional new features.

**Comment by oivio** [comment]
> Thank you very much for your response!

New demo update is up: https://www.youtube.com/watch?v=iCAe7dyy9dw

**Comment by k164v** [comment]
> 
> 
> > Thank you very much for your response!
> 
> New demo update is up: https://www.youtube.com/watch?v=iCAe7dyy9dw

These are some truly amazing examples! Very informative and complete. Thank you again for the amazing work!

**Comment by 823639792** [comment]
Hope to support 4.25

**Comment by 823639792** [comment]
Hope to support 4.25
