### ISSUE TITLE
 How to use IME input in blui???

### ISSUE THREAD

**Issue by lvhuming** [getnamo/BLUI#27]
WebBrowser can support this：
ITextInputMethodSystem* const TextInputMethodSystem = FSlateApplication::Get().GetTextInputMethodSystem();
WebBrowserWidget->BindInputMethodSystem(TextInputMethodSystem);

but simage not suppot this。

**Comment by lvhuming** [comment]
Maybe I can use OnImeCompositionRangeChanged, but it doesn't seem to work.

**Comment by getnamo** [comment]
What is the end result you're looking for? text input in a particular way?

**Comment by monkeykane** [comment]
Is there possible to use osr_ime_handler_win to custom IME input?
In off-screen mode, it seems that 'blu_ue4_process' could not receive windows message.

**Comment by lvhuming** [comment]
I finished it by referring to the input mode of official ime encapsulation

**Comment by Johnly1986** [comment]
> I finished it by referring to the input mode of official ime encapsulation

How did you solve this problem please?
