### ISSUE TITLE
getusermedia

### ISSUE THREAD

**Issue by oivio** [getnamo/BLUI#28]
I did try to work on getusermedia. Just to have a popup window for camera notification but I did stuck. If I do remember even native UE4 plugin has the same problem.  I did read that there might be a solution by using javascript. So I did try it but with no result. I think webcamtests.com is using something like that. Anyways. Did anyone try to achieve that goal?

**Comment by getnamo** [comment]
Latest version with update CEF now has a few settings on by default which relax security. You should be able to do a getusermedia (tested on showing a webcam locally, which worked)
