### ISSUE TITLE
UE4.24 - BLUI fails to recompile

### ISSUE THREAD

**Issue by luvtin** [getnamo/BLUI#35]
I can not rebuild BLUI in ue4.24.It said 'HTML5' is not a valid platform name.I tried to remove 'HTML5' character in BLUI.UPLUGIN,but it still had error. How can i deal with it.Thank u!

**Comment by getnamo** [comment]
You should be able to remove HTML5 from _both_ blacklistplatforms in https://github.com/getnamo/BLUI/blob/master/BLUI.uplugin. 4.24 removed the HTML5 platform from the engine and moved it into an engine extension

**Comment by luvtin** [comment]
Thank you for your reply.I had removed "HTML5" from both blacklistplatforms in BLUI.uplugin.BUT VS still had error : "MSB307 'WaitMutex -FromMsBuild' exited with code 5 . Please verify that you have sufficient rig"

**Comment by getnamo** [comment]
New release for 4.24: https://github.com/getnamo/BLUI/releases/tag/3.7.0

NB: the underlying CEF has been updated too so things might work differently
