### ISSUE TITLE
Crash: EXCEPTION_ACCESS_VIOLATION (WebBrowser Plugin needs to be turned off)

### ISSUE THREAD

**Issue by goldngood** [getnamo/BLUI#37]
`LoginId:26070d114dd244614ccb4d8bde604f7a
EpicAccountId:37a7bb96c5bb4322a658cee725c4aa66

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000024b

UE4Editor_Blu!std::vector<CefRect,std::allocator<CefRect> >::_Xlength()
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
libcef
UE4Editor_CoreUObject!UObject::execCallMathFunction() [d:\dev\unrealengine-angelscript\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:860]
UE4Editor_CoreUObject!ProcessLocalScriptFunction() [d:\dev\unrealengine-angelscript\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1011]
UE4Editor_CoreUObject!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [d:\dev\unrealengine-angelscript\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:828]
UE4Editor_CoreUObject!ProcessLocalFunction() [d:\dev\unrealengine-angelscript\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1079]
UE4Editor_CoreUObject!ProcessLocalScriptFunction() [d:\dev\unrealengine-angelscript\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1011]
UE4Editor_CoreUObject!UObject::ProcessInternal() [d:\dev\unrealengine-angelscript\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1104]
UE4Editor_CoreUObject!UFunction::Invoke() [d:\dev\unrealengine-angelscript\engine\source\runtime\coreuobject\private\uobject\class.cpp:4941]
UE4Editor_CoreUObject!UObject::ProcessEvent() [d:\dev\unrealengine-angelscript\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1946]
UE4Editor_Engine!AActor::ProcessEvent() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\actor.cpp:944]
UE4Editor_Engine!AActor::ReceiveTick() [d:\dev\unrealengine-angelscript\engine\intermediate\build\win64\ue4editor\inc\engine\actor.gen.cpp:1108]
UE4Editor_Engine!AActor::Tick() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\actor.cpp:1165]
UE4Editor_Engine!AActor::TickActor() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\actor.cpp:1145]
UE4Editor_Engine!FActorTickFunction::ExecuteTick() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\actor.cpp:168]
UE4Editor_Engine!FTickFunctionTask::DoTask() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\ticktaskmanager.cpp:285]
UE4Editor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\dev\unrealengine-angelscript\engine\source\runtime\core\public\async\taskgraphinterfaces.h:847]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\dev\unrealengine-angelscript\engine\source\runtime\core\private\async\taskgraph.cpp:686]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [d:\dev\unrealengine-angelscript\engine\source\runtime\core\private\async\taskgraph.cpp:583]
UE4Editor_Core!FTaskGraphImplementation::WaitUntilTasksComplete() [d:\dev\unrealengine-angelscript\engine\source\runtime\core\private\async\taskgraph.cpp:1465]
UE4Editor_Engine!FTickTaskSequencer::ReleaseTickGroup() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\ticktaskmanager.cpp:560]
UE4Editor_Engine!FTickTaskManager::RunTickGroup() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\ticktaskmanager.cpp:1528]
UE4Editor_Engine!UWorld::RunTickGroup() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\leveltick.cpp:782]
UE4Editor_Engine!UWorld::Tick() [d:\dev\unrealengine-angelscript\engine\source\runtime\engine\private\leveltick.cpp:1552]
UE4Editor_UnrealEd!UEditorEngine::Tick() [d:\dev\unrealengine-angelscript\engine\source\editor\unrealed\private\editorengine.cpp:1683]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [d:\dev\unrealengine-angelscript\engine\source\editor\unrealed\private\unrealedengine.cpp:410]
UE4Editor!FEngineLoop::Tick() [d:\dev\unrealengine-angelscript\engine\source\runtime\launch\private\launchengineloop.cpp:4485]
UE4Editor!GuardedMain() [d:\dev\unrealengine-angelscript\engine\source\runtime\launch\private\launch.cpp:173]
UE4Editor!GuardedMainWrapper() [d:\dev\unrealengine-angelscript\engine\source\runtime\launch\private\windows\launchwindows.cpp:134]
UE4Editor!WinMain() [d:\dev\unrealengine-angelscript\engine\source\runtime\launch\private\windows\launchwindows.cpp:263]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll`

**Comment by getnamo** [comment]
Disable WebBrowser plugin.
