### ISSUE TITLE
How to download a pdf file ??

### ISSUE THREAD

**Issue by GMAGD** [getnamo/BLUI#41]
i use download file and bind to on download update and complete but nothing happen i can't download the pdf file :'( ?? help

**Comment by getnamo** [comment]
Check your logs, it may have hints at what the root cause of your download could be

**Comment by GMAGD** [comment]
hey thx but I got no logs

**Comment by GMAGD** [comment]
Aren't u forgetting this  : 
`virtual CefRefPtr<CefDownloadHandler> GetDownloadHandler() override {

   		 return this;
	}`
in the RenderHandler.h
