### ISSUE TITLE
Wrong Key Codes For Arrow Keys (Can't Build)

### ISSUE THREAD

**Issue by aaron1a12** [getnamo/BLUI#44]
Hey, I forked and did a pull request to fix the wrong key codes that were entered in BluEye.h and I tried building myself but I couldn't because the builder.py seems really outdated.

What is "Patch"?

**Comment by getnamo** [comment]
I don't personally use builder.py. It looks related to CEF builds, which I do manually using the sparse instructions at https://github.com/getnamo/blubrowser

You should be able to change BluEye.h and hit compile in ue4 to update unreal side of the plugin.

**Comment by aaron1a12** [comment]
Oh great. I wasn't trying to rebuild CEF. Thanks.
