### ISSUE TITLE
blui on static mesh

### ISSUE THREAD

**Issue by ffreality** [getnamo/BLUI#47]
Does current version of Blui supports static mesh ? I can use it with widgets but even if I follow youtube tutorials, I can not get web view.

**Comment by getnamo** [comment]
BLUI (via the main BluEye) outputs a Texture2D, you can apply it to any surface including static meshes.

**Comment by getnamo** [comment]
You may want to look at a community project/video that shows this feature here: https://www.youtube.com/watch?v=iCAe7dyy9dw
