### ISSUE TITLE
Editor Crash After Spawning Blui Actor

### ISSUE THREAD

**Issue by ffreality** [getnamo/BLUI#53]
Editor Crashes After Spawning Blui Actor.

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION 0x9a2dc100

0x00007ffa9a2dc100 libcef.dll!UnknownFunction []
0x00007ffab93f51d8 UE4Editor-Blu.dll!UnknownFunction []
0x00007ffab93fd033 UE4Editor-Blu.dll!UnknownFunction []
0x00007ffa97054986 libcef.dll!UnknownFunction []
0x00007ffa97a8131e libcef.dll!UnknownFunction []
0x00007ffa97a80695 libcef.dll!UnknownFunction []
0x00007ffa97a80c9b libcef.dll!UnknownFunction []
0x00007ffa970435fe libcef.dll!UnknownFunction []
0x00007ffab93e03dc UE4Editor-Blu.dll!UnknownFunction []
0x00007ffab93ce546 UE4Editor-Blu.dll!UnknownFunction []
0x00007ffad1db0ae4 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad20000dd UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2023113 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad202574d UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad1ff3bea UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2025392 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2023113 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad202574d UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad1ff3bea UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2025392 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad202574d UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad1ff3bea UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2025392 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad202574d UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2024c54 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad1db0ae4 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2024783 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad275a025 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad27247db UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad27302fc UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad27564f2 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad273c59c UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad2e09d5e UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad3ad53c6 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad204a635 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad204ce7f UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad202574d UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2024c54 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad1db0ae4 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad2024783 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007ffad275a025 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad2fea528 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad2fcb57f UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad2772e28 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad2772f8a UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad27394c4 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad37f7e0f UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad37fce67 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad53f87d8 UE4Editor-Core.dll!UnknownFunction []
0x00007ffad53f8aa3 UE4Editor-Core.dll!UnknownFunction []
0x00007ffad540f027 UE4Editor-Core.dll!UnknownFunction []
0x00007ffad3818e52 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad381e11a UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad2fdbfff UE4Editor-Engine.dll!UnknownFunction []
0x00007ffad2fe6897 UE4Editor-Engine.dll!UnknownFunction []
0x00007ffacfe0af57 UE4Editor-UnrealEd.dll!UnknownFunction []
0x00007ffad06e1d06 UE4Editor-UnrealEd.dll!UnknownFunction []
0x00007ff6a9777800 UE4Editor.exe!UnknownFunction []
0x00007ff6a978ba7c UE4Editor.exe!UnknownFunction []
0x00007ff6a978bb5a UE4Editor.exe!UnknownFunction []
0x00007ff6a979e31d UE4Editor.exe!UnknownFunction []
0x00007ff6a97a145a UE4Editor.exe!UnknownFunction []
0x00007ffb359c6fd4 KERNEL32.DLL!UnknownFunction []
0x00007ffb365dcec1 ntdll.dll!UnknownFunction []

**Comment by getnamo** [comment]
This isn't enough to go on e.g. context, examples, platform & plugin versions, and steps to reproduce needed

**Comment by ffreality** [comment]
In UE 4.25
I created an empty blueprint project and copy your plugin to necessary location (Project's root/Plugins). I can see plugin is enabled in Plugins folder.

And dragged your example actor to viewport.
When I press to play, editor crashes.

OS is windows, target platform is desktop. Plugin version is 4.0

**Comment by getnamo** [comment]
Did you use the ```BLUI-v4.0.0-UE4.25.7z
``` release folder from https://github.com/getnamo/BLUI/releases/tag/4.0.0? (not source code zip)

**Comment by parthnaik92** [comment]
> In UE 4.25
> I created an empty blueprint project and copy your plugin to necessary location (Project's root/Plugins). I can see plugin is enabled in Plugins folder.
> 
> And dragged your example actor to viewport.
> When I press to play, editor crashes.
> 
> OS is windows, target platform is desktop. Plugin version is 4.0
> 
> --
> Also tried with C++ project and result is same.

This is happening to me too. UE 4.25. I used this:

> Did you use the `BLUI-v4.0.0-UE4.25.7z` release folder from https://github.com/getnamo/BLUI/releases/tag/4.0.0? (not source code zip)

**Comment by parthnaik92** [comment]
The issue was the "Web Browser" plugin. Make sure that the "Web Browser" plugin under the "Widgets" category is disabled. I think that the web browser plugin uses an older version of CEF so that might be conflicting with this plugin.

**Comment by Ty-lerCox** [comment]
@parthnaik92  this may be a common thing people run into after experimenting with other plugins.
