### ISSUE TITLE
Clicks are not working in 4.26

### ISSUE THREAD

**Issue by Ty-lerCox** [getnamo/BLUI#63]
I am using the 4.26 release out of the box and then binding a key to creating the widget. The widget and web page load but when I click into the widget it fails to fire a mouse click.
![image](https://user-images.githubusercontent.com/6323925/120082294-14b28700-c090-11eb-95e5-9107407a6acf.png)

**Comment by Ty-lerCox** [comment]
just kidding... <3
![image](https://user-images.githubusercontent.com/6323925/120082610-dd44da00-c091-11eb-8702-e71178e3419e.png)

**Comment by getnamo** [comment]
Great stuff
