### ISSUE TITLE
The issue in UE4.26 + Blui + CEF 4430 

### ISSUE THREAD

**Issue by TopDeveloper-333** [getnamo/BLUI#64]
Hello @getnamo 

I have trouble integrating Blui project into my UE 4.26 project by using CEF 4430 (latest stable version).  
The following is my way to integrate this.

1. CEF-4430 compilation
I compiled CEF 4430 by using automate-git.py by enable ffmpeg_branding, properietary_codecs options. 
Here, I compiled cefsimple by using ninja, and then update it by using https://github.com/uhrobots/BluBrowser, and then compiled blu_ue4_process.exe ( by renamed cefsimple)
At the blubrowser compilation time, I changed some codes to avoid issues such as browser->SendProcessMessage() => browser->GetMainFrame()->SendProcessMessage(),  frame->LoadString() => frame->LoadURL(....)

2. BLUI plugin into UE 4.26 project.
I copied the BLUI 4.1.0 into my UE project.  Here I used in CefBrowserHost::CreateBrowserSync()'s last parameter as CefRequestContext::GetGlobalContext() to avoid CEF crash.
also copied cefsimple or blu_ue4_process.exe and other libraries from CEF 4430 into ThirdParty/inc, lib, shipping directories

3. UE project
created new level, and new UMG and edit those blueprint like as following
![image](https://user-images.githubusercontent.com/69617937/121208507-1280d180-c8b5-11eb-8c52-aa6d3bece336.png)
![image](https://user-images.githubusercontent.com/69617937/121208652-2f1d0980-c8b5-11eb-9a3d-01fa44ced377.png)
![image](https://user-images.githubusercontent.com/69617937/121208729-3d6b2580-c8b5-11eb-8bcc-48db91071f0f.png)

4. The issue
4.1 HTML button is not clicked
when I use google.com, types keyword into edit and then enter press, it works, 
but if I type keyword and click google search button, it doesn't work (when i move mouse over button, button's outline color is changed blue; looks like not issue in mouse pos calculation)

4.2 RenderHandler's onPaint() is not called after some seconds.
I used original cefsimple and blubrowser as blu_ue4_process.exe, but same issue happened. I compared the cefsimple and blui source code, and only figured the difference in CefBrowserHost::CreateBrowserSync() function and CefBrowserHost::CreateBrowser()..

I hope to get your help.
Regards

**Comment by CHADALAK1** [comment]
I, too wish to know more about integrating a newer version of CEF into BLUI...

**Comment by JayArpeggios** [comment]
@TopDeveloper-333 I am also looking to update CEF because I need the audio data from CEF to integrate into unreal directly. Please post an update if you find any success.

**Comment by getnamo** [comment]
https://github.com/getnamo/BLUI/issues/29 these sparse notes were from the last time I updated CEF here.

**Comment by PeleglilaArti** [comment]
@TopDeveloper-333 Hi,
Do you have this version of CEF with codecs available and you can share? 
Thanks
