### ISSUE TITLE
CEF Process doesn't stop when using PIE

### ISSUE THREAD

**Issue by Derjyn** [getnamo/BLUI#7]
When testing from PIE, everything works fine.  However, when quitting, the CEF process doesn't end.

In my test, I was playing a "fullscreen" YouTube video.  When exiting, the PIE window closes, but the CEF process (`blu_ue4_process.exe`) continues on, and you can hear the video playing in the background.  Standalone or launching doesn't have this issue.

**Comment by getnamo** [comment]
Looking at https://github.com/getnamo/BLUI/blob/master/Source/Blu/Private/BluEye.cpp#L619 do you get 'Browser Closing' showing up in your logs?

It does look like ```renderer``` and ```g_handler``` don't get released either https://github.com/getnamo/BLUI/blob/master/Source/Blu/Private/BluEye.cpp#L61 would need to dig a bit deeper to see which of these (or others?) keep the blu process running.

**Comment by getnamo** [comment]
https://github.com/getnamo/BLUI/releases/tag/3.7.0 might've fixed this issue. Closing due to age.
