### ISSUE TITLE
Can't use BLUI with nodejs-ue4 and socketio-client-ue4

### ISSUE THREAD

**Issue by sylvqin** [getnamo/BLUI#71]
Hello getnamo, and first of all, thanks for the amazing plugins!
I tried to add BLUI (which i already used) on a new project which have both nodejs-ue4 and socketio-client-ue4, your other plugins.
I'm on UE5 and it seems that every time I try adding BLUI, my project crashes before starting :

```
Assertion failed: bSuccess [File:D:/build/++UE5/Sync/Engine/Source/Runtime/WebBrowser/Private/WebBrowserSingleton.cpp] [Line: 344]

UnrealEditor_WebBrowser
UnrealEditor_WebBrowser
UnrealEditor_Bridge
UnrealEditor_Bridge
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_MainFrame
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

I would need to use BLUI to show some web pages ingame. Any idea?

Thanks and happy new yar!

**Comment by sylvqin** [comment]
Nevermind, it was because Quixel Bridge plugin was activated, desactivating worked perfectly. My bad!

**Comment by sylvqin** [comment]
Nevermind, it was because Quixel Bridge plugin was activated, desactivating worked perfectly. My bad!

**Comment by getnamo** [comment]
Hah you really want all the V8 power 😎

Glad they work together as expected now. I believe quixel bridge depends on internal web browser module which clashes with BLUI for some reason.
